import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import {
  APP_NAME,
  APP_SUBTITLE,
  APP_TAGS,
  APP_DESCRIPTION,
} from "@/constants/app.constants";
import { getWalletDetails } from "@/hooks/getAddress.hook";

export default function Home() {
  return (
    <>
      <Head>
        <title>Deca=Org </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="splash-screen overflow-x-hidden text-center h-full w-full m-auto flex flex-col md:flex-row overflow-y-auto md:overflow-y-hidden ">
        <div className="md:w-1/3 h-fit order-2 md:order-1">
          <div className="text-[#94a3b8] text-md md:text-4xl px-7 py-12 mr-14 my-14">
            {APP_SUBTITLE}
          </div>
        </div>
        <div className="splash-screen-content min-h-fit relative p-2 md:h-2/3 w-3/4 m-auto sm:w-1/4 top-10 left-0 bg-gradient-to-r from-[#00101c] to-blue-500 rounded-2xl z-0 md:top-20 mt-12 order-1 md:order-2">
          <div className="splash-screen-content-inner relative h-full w-full z-10 flex flex-col justify-between">
            <div>
              <Image
                src="/images/Deca-Org Logo.png"
                alt="Team App Logo"
                className="splash-screen-content-inner-logo mx-auto mt-6 p-4 sm:p hover:shadow-lg rounded-full hover:px-3 hover:py-3"
                width={350}
                height={350}
              />
            </div>
            <div className="splash-screen-content-inner-title text-white text-4xl md:text-6xl md:hover:text-5xl mt-5 font-bold">
              {APP_NAME}
            </div>
            <div className="splash-screen-content-inner-subtitle text-[#cbd5e1] text-sm md:text-md hover:text-2xl mb-2 pt-2 font-bold">
              {APP_TAGS}
            </div>
          </div>
        </div>
        <div className="w-3/4 mx-auto md:mx-0 md:w-1/3 h-screen relative top-20 mt-10 flex flex-col order-3 md:order-3">
          <div className="md:h-1/3 hidden md:flex"></div>
          <div className="md:h-1/3 hidden md:flex"></div>
          <div className="md:h-1/3 hidden md:flex"></div>
          <div className="bg-blue h-screen w-full justify-end m">
            <button
              type="button"
              className="md:mt-12 w-full md:w-1/2 h-20 text-white bg-gradient-to-r from-purple-500 to-pink-500 hover:bg-gradient-to-l focus:ring-4 focus:outline-none focus:ring-purple-200 dark:focus:ring-purple-800 rounded-lg text-2xl px-5 py-2.5 text-center mr-2 mb-2"
              onClick={async () => {
                const { address } = await getWalletDetails();
                if (address) window.location.href = "/login";
              }}
            >
              <pre className="text-sm">Connect with us!</pre>
              Connect wallet
            </button>
            <br />
            {/* <Link href= '/signup'>
            <button
              type="button"
              className="mt-5 w-full md:w-1/2 h-20 text-white bg-gradient-to-br from-pink-500 to-orange-400 hover:bg-gradient-to-bl focus:ring-4 focus:outline-none focus:ring-pink-200 dark:focus:ring-pink-800  rounded-lg text-2xl px-5 py-2.5 text-center mr-2 mb-2"
            >
              <pre className="text-sm">New to us?</pre>
              Sign-up
            </button>
            </Link> */}
          </div>
        </div>
      </div>
    </>
  );
}
